import React from 'react';
import { ShieldCheck, Lock, Trash2, Key, CheckCircle2, ArrowRight } from 'lucide-react';
import securityVaultImg from '../assets/images/security_vault_3d_1790800897430.jpg';

interface Security3DVaultProps {
  onOpenAuditCenter: () => void;
}

export const Security3DVault: React.FC<Security3DVaultProps> = ({ onOpenAuditCenter }) => {
  const securityPillars = [
    {
      title: 'AES-256-GCM Encryption',
      desc: 'Sensitive files are sealed using authenticated symmetric encryption with 96-bit unique IVs and integrity authentication tags.',
      icon: <Lock className="w-5 h-5 text-cyan-400" />
    },
    {
      title: 'Zero Remote Data Egress',
      desc: 'All conversion engines run locally inside your browser via WebAssembly. Your files never touch external servers or third-party AI models.',
      icon: <ShieldCheck className="w-5 h-5 text-emerald-400" />
    },
    {
      title: 'Cryptographic SHA-256 Integrity',
      desc: 'Every generated byte stream is verified against bit-level corruption and malicious payload tampering.',
      icon: <Key className="w-5 h-5 text-violet-400" />
    },
    {
      title: 'Instant Ephemeral Cleanup',
      desc: 'Memory objects, WebGL textures, and object URLs auto-purge upon tab closure or immediate user deletion.',
      icon: <Trash2 className="w-5 h-5 text-rose-400" />
    }
  ];

  return (
    <section className="relative w-full py-16 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto">
      <div className="rounded-3xl glass-surface-elevated border border-slate-200/80 dark:border-slate-800/80 bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 p-8 sm:p-12 overflow-hidden relative">
        {/* Ambient Radial Gradient Background */}
        <div className="absolute top-0 right-0 w-[30rem] h-[30rem] bg-emerald-500/10 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute bottom-0 left-0 w-[30rem] h-[30rem] bg-cyan-500/10 rounded-full blur-3xl pointer-events-none" />

        <div className="relative z-10 grid grid-cols-1 lg:grid-cols-12 gap-10 items-center">
          {/* Left Column: 3D Visual Asset Container */}
          <div className="lg:col-span-5 relative flex items-center justify-center">
            <div className="relative rounded-2xl overflow-hidden border border-slate-700/80 shadow-2xl group w-full max-w-md aspect-[4/3]">
              <img
                src={securityVaultImg}
                alt="3D Holographic Document Security Vault"
                referrerPolicy="no-referrer"
                className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-slate-950/90 via-transparent to-transparent pointer-events-none" />
              <div className="absolute bottom-4 left-4 right-4 flex items-center justify-between text-xs text-slate-300">
                <span className="font-semibold flex items-center space-x-1.5">
                  <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse"></span>
                  <span>Hardware-Level Sandbox Active</span>
                </span>
                <span className="font-mono text-cyan-400 text-[11px]">OWASP TOP 10</span>
              </div>
            </div>
          </div>

          {/* Right Column: Security Narrative & Controls */}
          <div className="lg:col-span-7 space-y-6">
            <div className="inline-flex items-center space-x-2 text-xs font-semibold text-emerald-400 bg-emerald-950/40 border border-emerald-800/40 px-3 py-1.5 rounded-lg">
              <ShieldCheck className="w-3.5 h-3.5" />
              <span>Full Data-Privacy & Integrity Architecture</span>
            </div>

            <h2 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight font-display text-balance">
              Your Files <span className="bg-gradient-to-r from-emerald-400 via-cyan-400 to-sky-400 bg-clip-text text-transparent">Stay Yours.</span>
            </h2>

            <p className="text-slate-300 text-sm sm:text-base leading-relaxed">
              We treat security as the foundational layer of ConvertAnyFile. Zero tracking telemetry, zero unauthorized file retention, and complete mathematical protection against cross-user exposure.
            </p>

            {/* 4 Security Pillars Grid */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2">
              {securityPillars.map(pillar => (
                <div
                  key={pillar.title}
                  className="p-4 rounded-xl glass-surface border border-slate-700/60 space-y-1.5"
                >
                  <div className="flex items-center space-x-2 text-white font-semibold text-sm">
                    {pillar.icon}
                    <span>{pillar.title}</span>
                  </div>
                  <p className="text-xs text-slate-400 leading-relaxed">
                    {pillar.desc}
                  </p>
                </div>
              ))}
            </div>

            <div className="pt-2 flex flex-wrap items-center gap-4">
              <button
                onClick={onOpenAuditCenter}
                className="px-5 py-2.5 text-xs font-bold text-white bg-slate-800 hover:bg-slate-700 border border-slate-600 rounded-xl transition-colors flex items-center space-x-2 shadow-sm"
              >
                <span>Run Interactive Security Audit</span>
                <ArrowRight className="w-3.5 h-3.5 text-cyan-400" />
              </button>
              <div className="flex items-center space-x-2 text-xs text-slate-400">
                <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                <span>20+ Automated Security Verification Checks</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};
